M48
; DRILL file {KiCad 8.0.7} date 2025-10-25T23:35:46+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-10-25T23:35:46+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.9459Y-2.2969
X4.9459Y-2.5244
T2
X3.7492Y-2.8437
X5.0091Y-1.9776
M30
